# Generated by Django 5.2.5 on 2025-08-22 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_book_cover_book_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Autorius', 'verbose_name_plural': 'Autoriai'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Knyga', 'verbose_name_plural': 'Knygos'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Žanras', 'verbose_name_plural': 'Žanrai'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Įvertinimas', 'verbose_name_plural': 'Įvertinimai'},
        ),
        migrations.AlterModelOptions(
            name='userbookstatus',
            options={'verbose_name': 'Knygos statusas', 'verbose_name_plural': 'Knygų statusai'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Vartotojo profilis', 'verbose_name_plural': 'Vartotojų profiliai'},
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gimimo metai'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Šalis/Miestas'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Vardas, pavardė'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='libraryapp.author', verbose_name='Autorius'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Viršelis'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='libraryapp.genre', verbose_name='Žanrai'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True, verbose_name='ISBN kodas'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Išleidimo metai'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Žanras'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='libraryapp.book', verbose_name='Knyga'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukurta'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Įvertinimas (žvaigždutės)'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
        migrations.AlterField(
            model_name='userbookstatus',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='libraryapp.book', verbose_name='Knyga'),
        ),
        migrations.AlterField(
            model_name='userbookstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukurta'),
        ),
        migrations.AlterField(
            model_name='userbookstatus',
            name='status',
            field=models.CharField(choices=[('read', 'Perskaityta'), ('want', 'Noriu perskaityti'), ('reading', 'Skaitau dabar')], default='read', max_length=20, verbose_name='Statusas'),
        ),
        migrations.AlterField(
            model_name='userbookstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gimimo metai'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Miestas'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
    ]
